version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:2.7.1
    steps:
      - checkout
      - run: rm -f Gemfile.lock && bundle install
      - run: rake test:all
      - store_artifacts:
          path: workflow/tests/test_results
          destination: results